version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # Enable BuildKit for faster builds
      target: production
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}
      # Add other environment variables as needed
    volumes:
      # Mount config files if needed
      - ./config:/app/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits to prevent OOM
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G